#!/usr/bin/env bash


usage() {

	cat <<-EOF

	usage: $0 destination-directory

	example script that charts CSV data that has been generated from sar
	Excel XLXS files with charts are produced

	applicable to any CSV data

	
	example: sar-chart.sh data-dir

	This script is using data generated by asp.sh


	EOF

}

cleanedFilePart='-cleaned'
replaceFilePart=''


while getopts ch arg
do
	case $arg in
		c) replaceFilePart=$cleanedFilePart;shift;;
		h) usage;exit 0;;
		*) usage;exit 1;;
	esac
done

srcDir=${1:-$(pwd)/csv} && cd $srcDir || {
	echo
	echo Cannot access source directory: $srcDir
	echo
	exit 1
}


cd $srcDir/.. || {
	echo
	echo Cannot access source directory parent: $srcDir
	echo
	exit 1
}


destDir=${2:-$(dirname ${srcDir})/sar-charts}


echo Source directory: $srcDir
echo Destination directory: $destDir


[ -d "$srcDir" -a -r "$srcDir" ] || {
	echo
	echo Cannot access "$srcDir"
	echo
	exit 1
}

mkdir -p $destDir

[ -d "$destDir" -a -w "$destDir" ] || {
	echo
	echo cannot read and/or write directory destDir: $destDir
	echo
	usage
	echo
	exit 1
}


### Template
#echo working on sar-
#dynachart.pl --spreadsheet-file ${destDir}/ --worksheet-col hostname --category-col 'timestamp' 
################


# if dynachart.pl is in the path then use it.
# if not then check for local directory copy or link
# otherwise error exit

dynaChart=$(which dynachart.pl)

if [[ -z $dynaChart ]]; then
	if [[ -f ./dynachart.pl ]]; then
		dynaChart='./dynachart.pl'
		[ -x "$dynaChart" ] || {
			echo
			echo $dynaChart is not executable	
			echo
			exit 2
		}
	else
		echo
		echo "dynachart.pl not found"
		echo
		exit 1
	fi
fi


# default of 1 chart per metric
#echo working on sar-disk-default${replaceFilePart}.xlsx
#dynachart.pl --spreadsheet-file ${destDir}/sar-disk-default${replaceFilePart}.xlsx --worksheet-col DEV --category-col 'timestamp' --chart-cols 'rd_sec/s' --chart-cols 'wr_sec/s' < sar-disk${replaceFilePart}.csv

# combine metrics into one chart
#echo working on sar-disk-combined${replaceFilePart}.xlsx
#dynachart.pl --spreadsheet-file ${destDir}/sar-disk-combined${replaceFilePart}.xlsx --combined-chart --worksheet-col DEV --category-col 'timestamp' --chart-cols 'rd_sec/s' --chart-cols 'wr_sec/s' < sar-disk${replaceFilePart}.csv

#:<<'COMMENT'

declare -A csvFiles=(
	["sar-network-device${replaceFilePart}.xlsx"]="sar-net-dev${replaceFilePart}.csv"
	["sar-network-error-device${replaceFilePart}.xlsx"]="sar-net-ede${replaceFilePart}.csv"
	["sar-network-nfs${replaceFilePart}.xlsx"]="sar-net-nfs${replaceFilePart}.csv"
	["sar-network-nfsd${replaceFilePart}.xlsx"]="sar-net-nfsd${replaceFilePart}.csv"
	["sar-network-socket${replaceFilePart}.xlsx"]="sar-net-sock${replaceFilePart}.csv"
	["sar-context${replaceFilePart}.xlsx"]="sar-context${replaceFilePart}.csv"
	["sar-cpu${replaceFilePart}.xlsx"]="sar-cpu${replaceFilePart}.csv"
	["sar-cpu-combined${replaceFilePart}.xlsx"]="sar-cpu${replaceFilePart}.csv"
	["sar-io-default${replaceFilePart}.xlsx"]="sar-io${replaceFilePart}.csv"
	["sar-io-tps-combined${replaceFilePart}.xlsx"]="sar-io${replaceFilePart}.csv"
	["sar-io-blks-per-second-combined${replaceFilePart}.xlsx"]="sar-io${replaceFilePart}.csv"
	["sar-load-runq-threads${replaceFilePart}.xlsx"]="sar-load${replaceFilePart}.csv"
	["sar-load-runq${replaceFilePart}.xlsx"]="sar-load${replaceFilePart}.csv"
	["sar-memory${replaceFilePart}.xlsx"]="sar-mem${replaceFilePart}.csv"
	["sar-mem-utilization${replaceFilePart}.xlsx"]="sar-mem-utilization${replaceFilePart}.csv"
	["sar-hugepages-utilization${replaceFilePart}.xlsx"]="sar-hugepages-utilization${replaceFilePart}.csv"
	["sar-paging-rate${replaceFilePart}.xlsx"]="sar-paging${replaceFilePart}.csv"
	["sar-swap-rate${replaceFilePart}.xlsx"]="sar-swap-stats${replaceFilePart}.csv"
	["sar-swap-utilization${replaceFilePart}.xlsx"]="sar-swap-utilization${replaceFilePart}.csv"
	["sar-kernel-fs${replaceFilePart}.xlsx"]="sar-kernel-fs${replaceFilePart}.csv"
)

declare -A csvArgs=(
	["sar-network-device${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col IFACE --category-col 'timestamp' --chart-cols 'rxkB/s' --chart-cols 'txkB/s'"
	["sar-network-error-device${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col IFACE --category-col 'timestamp' --chart-cols 'rxerr/s' --chart-cols 'txerr/s'"
	["sar-network-nfs${replaceFilePart}.xlsx"]="--worksheet-col hostname --category-col 'timestamp' --chart-cols 'call/s' --chart-cols 'retrans/s' --chart-cols 'read/s' --chart-cols 'write/s' --chart-cols 'access/s' --chart-cols 'getatt/s'"
	["sar-network-nfsd${replaceFilePart}.xlsx"]="--worksheet-col hostname --category-col 'timestamp' --chart-cols 'scall/s' --chart-cols 'badcall/s' --chart-cols 'packet/s' --chart-cols 'udp/s' --chart-cols 'tcp/s' --chart-cols 'hit/s' --chart-cols 'miss/s' --chart-cols 'sread/s' --chart-cols 'swrite/s' --chart-cols 'saccess/s' --chart-cols 'sgetatt/s'"
	["sar-network-socket${replaceFilePart}.xlsx"]="--worksheet-col hostname --category-col 'timestamp' --chart-cols 'totsck' --chart-cols 'tcpsck' --chart-cols 'udpsck' --chart-cols 'rawsck' --chart-cols 'ip-frag' --chart-cols 'tcp-tw'"
	["sar-context${replaceFilePart}.xlsx"]="--worksheet-col hostname --category-col 'timestamp' --chart-cols 'proc/s' --chart-cols 'cswch/s'"
	["sar-cpu${replaceFilePart}.xlsx"]="--worksheet-col hostname --category-col 'timestamp' --chart-cols '%usr' --chart-cols '%nice' --chart-cols '%sys' --chart-cols '%iowait' --chart-cols '%steal' --chart-cols '%irq' --chart-cols '%soft' --chart-cols '%guest' --chart-cols '%idle'"
	["sar-cpu-combined${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col hostname --category-col 'timestamp' --chart-cols '%usr' --chart-cols '%nice' --chart-cols '%sys' --chart-cols '%iowait' --chart-cols '%steal' --chart-cols '%irq' --chart-cols '%soft' --chart-cols '%guest' --chart-cols '%idle'"
	["sar-io-default${replaceFilePart}.xlsx"]="--worksheet-col hostname --category-col 'timestamp' --chart-cols 'tps' --chart-cols 'rtps' --chart-cols 'wtps' --chart-cols 'bread/s' --chart-cols 'bwrtn/s'"
	["sar-io-tps-combined${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col hostname --category-col 'timestamp' --chart-cols 'tps' --chart-cols 'rtps' --chart-cols 'wtps'"
	["sar-io-blks-per-second-combined${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col hostname --category-col 'timestamp' --chart-cols 'bread/s' --chart-cols 'bwrtn/s'"
	["sar-load-runq-threads${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col hostname --category-col 'timestamp' --chart-cols 'runq-sz' --chart-cols 'plist-sz' --chart-cols 'ldavg-1' --chart-cols 'ldavg-5' --chart-cols 'ldavg-15'"
	["sar-load-runq${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col hostname --category-col 'timestamp' --chart-cols 'runq-sz' --chart-cols 'ldavg-1' --chart-cols 'ldavg-5' --chart-cols 'ldavg-15'"
	["sar-memory${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col hostname --category-col 'timestamp' --chart-cols 'frmpg/s' --chart-cols  'bufpg/s'"
	["sar-mem-utilization${replaceFilePart}.xlsx"]="--worksheet-col hostname --category-col 'timestamp' --chart-cols '%commit' --chart-cols 'kbcommit' --chart-cols 'kbmemfree' --chart-cols  'kbmemused' --chart-cols 'kbcached'"
	["sar-hugepages-utilization${replaceFilePart}.xlsx"]="--worksheet-col hostname --category-col 'timestamp' --chart-cols 'kbhugfree' --chart-cols 'kbhugused' --chart-cols '%hugused'"
	["sar-paging-rate${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col hostname --category-col 'timestamp'  --chart-cols 'pgpgin/s' --chart-cols  'pgpgout/s'"
	["sar-swap-rate${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col hostname --category-col 'timestamp'  --chart-cols 'pswpin/s' --chart-cols 'pswpout/s'"
	["sar-swap-utilization${replaceFilePart}.xlsx"]="--combined-chart --worksheet-col hostname --category-col 'timestamp' --chart-cols 'kbswpfree' --chart-cols 'kbswpused' --chart-cols '%swpused' --chart-cols 'kbswpcad' --chart-cols '%swpcad'"
	["sar-kernel-fs${replaceFilePart}.xlsx"]="--worksheet-col hostname --category-col 'timestamp' --chart-cols 'dentunusd' --chart-cols 'file-nr' --chart-cols 'inode-nr' --chart-cols 'pty-nr'"
)

for key in "${!csvFiles[@]}"; do
	value=${csvFiles[$key]}
	echo "$key => $value"
done

for key in "${!csvArgs[@]}"; do
	value=${csvArgs[$key]}
	echo "$key => $value"
done



exit

for spreadsheet in "${!csvFiles[@]}"; do
	csvFile=${csvFiles[$spreadsheet]}
	args=${csvArgs[$spreadsheet]}
	
	echo working on $spreadsheet
	[[ -f "$srcDir/$csvFile" ]] || {
		echo "Source CSV file $srcDir/$csvFile not found, skipping $spreadsheet"
		continue	
	}

	[[ -s "$srcDir/$csvFile" ]] || {
		echo "Source CSV file $srcDir/$csvFile is empty, skipping $spreadsheet"
		continue	
	}

	eval "dynachart.pl --spreadsheet-file ${destDir}/$spreadsheet $args < "$srcDir"/$csvFile"

done



