#!/usr/bin/env bash


usage() {

	cat <<-EOF

	usage: $0 destination-directory

	example script that charts CSV data that has been generated from sar
	Excel XLXS files with charts are produced

	applicable to any CSV data
	
   -d destination-directory
      Directory where the generated Excel files will be placed
      Defaults to ../sar-charts

   -s source-directory
      Directory where the CSV files are located
      Defaults to ./csv

	example: sar-chart.sh -s data-dir

	This script is using data generated by asp.sh

	EOF

}

SAR_DEBUG=${SAR_DEBUG:-0}

sdebug() {
	[[ $SAR_DEBUG -eq 1 ]] && echo "$@"
}

csvHomeDir=${csvHomeDir:-$(pwd)}

cd $csvHomeDir || {
	echo
	echo Cannot access csvHomeDir: $csvHomeDir
	echo
	exit 1
}

sdebug "csvHomeDir: $csvHomeDir"

srcDir='csv'
destDir='sar-charts'

while getopts s:d:h arg
do
	case $arg in
		s) srcDir=$OPTARG;;
		d) destDir=$OPTARG;;
		h) usage;exit 0;;
		*) usage;exit 1;;
	esac

done

cd $srcDir || {
	echo
	echo Cannot access source directory: $srcDir
	echo
	exit 1
}

sdebug "PWD: $(pwd)"
sdebug "srcDir: $srcDir"

cd .. || {
	echo
	echo Cannot access source directory parent: $srcDir
	echo
	exit 1
}

destDir=${destDir:-$(dirname ${srcDir})/sar-charts}

echo Source directory: $srcDir
echo Destination directory: $destDir

[ -d "$srcDir" -a -r "$srcDir" ] || {
	echo
	echo Cannot access "$srcDir"
	echo
	exit 1
}

mkdir -p $destDir

[ -d "$destDir" -a -w "$destDir" ] || {
	echo
	echo cannot read and/or write directory destDir: $destDir
	echo
	usage
	echo
	exit 1
}

### Template
#echo working on sar-
#dynachart.pl --spreadsheet-file ${destDir}/ --worksheet-col hostname --category-col 'timestamp' 
################


# if dynachart.pl is in the path then use it.
# if not then check for local directory copy or link
# otherwise error exit

dynaChart=$(which dynachart.pl)

if [[ -z $dynaChart ]]; then
	if [[ -f ./dynachart.pl ]]; then
		dynaChart='./dynachart.pl'
		[ -x "$dynaChart" ] || {
			echo
			echo $dynaChart is not executable	
			echo
			exit 2
		}
	else
		echo
		echo "dynachart.pl not found"
		echo
		exit 1
	fi
fi


# default of 1 chart per metric
#echo working on sar-disk-default.xlsx
#dynachart.pl --spreadsheet-file ${destDir}/sar-disk-default.xlsx --worksheet-col DEV --category-col 'timestamp' --chart-cols 'rd_sec/s' --chart-cols 'wr_sec/s' < sar-disk.csv

# combine metrics into one chart
#echo working on sar-disk-combined.xlsx
#dynachart.pl --spreadsheet-file ${destDir}/sar-disk-combined.xlsx --combined-chart --worksheet-col DEV --category-col 'timestamp' --chart-cols 'rd_sec/s' --chart-cols 'wr_sec/s' < sar-disk.csv

#:<<'COMMENT'

declare -A csvFiles=(
	["sar-network-device.xlsx"]="sar-net-dev.csv"
	["sar-network-error-device.xlsx"]="sar-net-ede.csv"
	["sar-network-nfs.xlsx"]="sar-net-nfs.csv"
	["sar-network-nfsd.xlsx"]="sar-net-nfsd.csv"
	["sar-network-socket.xlsx"]="sar-net-sock.csv"
	["sar-context.xlsx"]="sar-context.csv"
	["sar-cpu.xlsx"]="sar-cpu.csv"
	["sar-cpu-combined.xlsx"]="sar-cpu.csv"
	["sar-io-default.xlsx"]="sar-io.csv"
	["sar-io-tps-combined.xlsx"]="sar-io.csv"
	["sar-io-blks-per-second-combined.xlsx"]="sar-io.csv"
	["sar-load-runq-threads.xlsx"]="sar-load.csv"
	["sar-load-runq.xlsx"]="sar-load.csv"
	["sar-memory.xlsx"]="sar-mem.csv"
	["sar-mem-utilization.xlsx"]="sar-mem-utilization.csv"
	["sar-hugepages-utilization.xlsx"]="sar-hugepages-utilization.csv"
	["sar-paging-rate.xlsx"]="sar-paging.csv"
	["sar-swap-rate.xlsx"]="sar-swap-stats.csv"
	["sar-swap-utilization.xlsx"]="sar-swap-utilization.csv"
	["sar-kernel-fs.xlsx"]="sar-kernel-fs.csv"
)

declare -A csvArgs=(
	["sar-network-device.xlsx"]="--combined-chart --worksheet-col IFACE --category-col timestamp --chart-cols rxkB/s --chart-cols txkB/s"
	["sar-network-error-device.xlsx"]="--combined-chart --worksheet-col IFACE --category-col timestamp --chart-cols rxerr/s --chart-cols txerr/s"
	["sar-network-nfs.xlsx"]="--worksheet-col hostname --category-col timestamp --chart-cols call/s --chart-cols retrans/s --chart-cols read/s --chart-cols write/s --chart-cols access/s --chart-cols getatt/s"
	["sar-network-nfsd.xlsx"]="--worksheet-col hostname --category-col timestamp --chart-cols scall/s --chart-cols badcall/s --chart-cols packet/s --chart-cols udp/s --chart-cols tcp/s --chart-cols hit/s --chart-cols miss/s --chart-cols sread/s --chart-cols swrite/s --chart-cols saccess/s --chart-cols sgetatt/s"
	["sar-network-socket.xlsx"]="--worksheet-col hostname --category-col timestamp --chart-cols totsck --chart-cols tcpsck --chart-cols udpsck --chart-cols rawsck --chart-cols ip-frag --chart-cols tcp-tw"
	["sar-context.xlsx"]="--worksheet-col hostname --category-col timestamp --chart-cols proc/s --chart-cols cswch/s"
	["sar-cpu.xlsx"]="--worksheet-col hostname --category-col timestamp --chart-cols %usr --chart-cols %nice --chart-cols %sys --chart-cols %iowait --chart-cols %steal --chart-cols %irq --chart-cols %soft --chart-cols %guest --chart-cols %idle"
	["sar-cpu-combined.xlsx"]="--combined-chart --worksheet-col hostname --category-col timestamp --chart-cols %usr --chart-cols %nice --chart-cols %sys --chart-cols %iowait --chart-cols %steal --chart-cols %irq --chart-cols %soft --chart-cols %guest --chart-cols %idle"
	["sar-io-default.xlsx"]="--worksheet-col hostname --category-col timestamp --chart-cols tps --chart-cols rtps --chart-cols wtps --chart-cols bread/s --chart-cols bwrtn/s"
	["sar-io-tps-combined.xlsx"]="--combined-chart --worksheet-col hostname --category-col timestamp --chart-cols tps --chart-cols rtps --chart-cols wtps"
	["sar-io-blks-per-second-combined.xlsx"]="--combined-chart --worksheet-col hostname --category-col timestamp --chart-cols bread/s --chart-cols bwrtn/s"
	["sar-load-runq-threads.xlsx"]="--combined-chart --worksheet-col hostname --category-col timestamp --chart-cols runq-sz --chart-cols plist-sz --chart-cols ldavg-1 --chart-cols ldavg-5 --chart-cols ldavg-15"
	["sar-load-runq.xlsx"]="--combined-chart --worksheet-col hostname --category-col timestamp --chart-cols runq-sz --chart-cols ldavg-1 --chart-cols ldavg-5 --chart-cols ldavg-15"
	["sar-memory.xlsx"]="--combined-chart --worksheet-col hostname --category-col timestamp --chart-cols frmpg/s --chart-cols  bufpg/s"
	["sar-mem-utilization.xlsx"]="--worksheet-col hostname --category-col timestamp --chart-cols %commit --chart-cols kbcommit --chart-cols kbmemfree --chart-cols  kbmemused --chart-cols kbcached"
	["sar-hugepages-utilization.xlsx"]="--worksheet-col hostname --category-col timestamp --chart-cols kbhugfree --chart-cols kbhugused --chart-cols %hugused"
	["sar-paging-rate.xlsx"]="--combined-chart --worksheet-col hostname --category-col timestamp  --chart-cols pgpgin/s --chart-cols  pgpgout/s"
	["sar-swap-rate.xlsx"]="--combined-chart --worksheet-col hostname --category-col timestamp  --chart-cols pswpin/s --chart-cols pswpout/s"
	["sar-swap-utilization.xlsx"]="--combined-chart --worksheet-col hostname --category-col timestamp --chart-cols kbswpfree --chart-cols kbswpused --chart-cols %swpused --chart-cols kbswpcad --chart-cols %swpcad"
	["sar-kernel-fs.xlsx"]="--worksheet-col hostname --category-col timestamp --chart-cols dentunusd --chart-cols file-nr --chart-cols inode-nr --chart-cols pty-nr"
)

for key in "${!csvFiles[@]}"; do
	value=${csvFiles[$key]}
	echo "$key => $value"
done

for key in "${!csvArgs[@]}"; do
	value=${csvArgs[$key]}
	echo "$key => $value"
done

declare -A fileIsClean

# used to track if LINUX-RESTART and extra header lines have been removed from the source CSV file
# there are some duplicate csv source file names, but that is ok
for csvFile in "${csvFiles[@]}"; do
	fileIsClean["$srcDir/$csvFile"]=0
done

for spreadsheet in "${!csvFiles[@]}"; do
	csvFile=${csvFiles[$spreadsheet]}
	args=${csvArgs[$spreadsheet]}
	
	echo working on $spreadsheet
	[[ -f "$srcDir/$csvFile" ]] || {
		echo "Source CSV file $srcDir/$csvFile not found, skipping $spreadsheet"
		continue	
	}

	[[ -s "$srcDir/$csvFile" ]] || {
		echo "Source CSV file $srcDir/$csvFile is empty, skipping $spreadsheet"
		continue	
	}

	declare -a argsArray=($args)
	# Check if the arguments contain --combined-chart
	if [[ " ${argsArray[@]} " =~ " --combined-chart " ]]; then
		echo "Generating combined chart for $spreadsheet"
	else
		echo "Generating individual charts for $spreadsheet"
	fi

	if [[ fileIsClean["$srcDir/$csvFile"] -eq 0 ]]; then

		grep -Em 1 '(^#\s+hostname|LINUX-RESTART)' "$srcDir/$csvFile" > /dev/null && {

			echo 
			echo "Source CSV file $srcDir/$csvFile has multiple header lines due to LINUX RESTART - cleaning the file to remove extra header lines"
			sed -r -i.bak '/(^#\s+hostname|LINUX-RESTART)/d' "$srcDir/$csvFile"
		
		} 

		fileIsClean["$srcDir/$csvFile"]=1

	fi

	declare -a dynachartCommand=("dynachart.pl" "--spreadsheet-file" "${destDir}/$spreadsheet")
	# Append the arguments to the command array
	dynachartCommand+=("${argsArray[@]}")
	# now execute the command
	sdebug CMD: "${dynachartCommand[@]}  <  $srcDir/$csvFile"
	"${dynachartCommand[@]}" < "$srcDir/$csvFile"

done



